### ISSUE TITLE
[Crash 1.19.2-v1.0.2] Crashing on World Load

### ISSUE THREAD

**Issue by SaltSouls** [Xaidee/Zombie-Friends#2] opened 2022-11-05 11:14 UTC
So I created a world, and after trying to open the debug display the game crashed. After restarting the game and trying to reload the world, the game crashed again. This mod seems to be listed as the main culprit and it would seem to have something to do with the rendering?

F3 Crash: [crash-2022-11-05_03.53.30-client.txt](https://github.com/Xaidee/Zombie-Friends/files/9943608/crash-2022-11-05_03.53.30-client.txt)
World Load Crash: [crash-2022-11-05_03.59.08-client.txt](https://github.com/Xaidee/Zombie-Friends/files/9943607/crash-2022-11-05_03.59.08-client.txt)

**Comment by Xaidee** [comment] 2022-11-05 11:19
Duplicate of #1. It has something to do with the way it compiled where the getUUID function that's supposed to be in the Entity class is being called by the wrong address or something, honestly I don't fully understand the bug especially since it's hard to replicate and not everyone seems to be having this crash but those that do have it consistently. As soon as I figure out exactly why this is happening I will fix it, in the mean time I suggest seeing if any of the previous versions work as some have found some ones work for them and some don't, i.e. 1.0.0, 1.0.1, 1.0.2

**Closed as completed by Xaidee** 2022-11-05 11:19 UTC
